### PR TITLE
Improve the docs index page

### PR DESCRIPTION
**Pull request by audreyfeldroy**
This PR fills in gaps in the homepage of docs.fastht.ml

* Crafted some nice intro text. I did my best to keep it concise and minimize redundancy.
* Expanded Next Steps with more about the resources, first community link, etc.

### CODE REVIEW

**Review by pydanny — APPROVED** [review]
LGTM!

**Comment by audreyfeldroy** [comment]
Actually I just saw items in our discussion that haven't been added yet. Please hold off until I get those in

**Comment by audreyfeldroy** [comment]
Didn't get a chance to address the remaining points we discussed, and feeling a bit tired. 

@jph00 Go ahead and merge this as an incremental change (or reject), and take it from here. As always I promise not to be offended if you rewrite it completely 🙂

**Comment by jph00** [comment]
This is super helpful thank you!

**Pull request merged**
