### PR TITLE
Example: Simple CRUD App - #131

### PR DESCRIPTION
**Pull request by RohitMidha23**
Example App to demonstrate CRUD functionality - for issue #131

### CODE REVIEW

**Comment by jph00** [comment]
Good job @RohitMidha23! I think rather than putting this in the main repo, it would be more effective to showcase it as a community contribution -- that way you can create a readme or blog post showing what the finished app looks like, how it works, etc. Would that be OK? If you did that we'd be delighted to highlight it!

**Comment by RohitMidha23** [comment]
@jph00 this particular example feels too simple to have as a separate blog post imo. Can work on a more complex one maybe but can’t commit as yet. If you have any ideas for that one, let me know!

**Comment by jph00** [comment]
I don't agree! I think it's great :D But up to you of course...

**Comment by GirishKumarSharma** [comment]
I think @RohitMidha23 is right. A more extended example will include Date, Short Notes, Boolean and Image data types by including some more common controls like Combo Box, Check box, Option button, Toggle button etc. So that it may increase its usability as well.

**Comment by jph00** [comment]
Sure -- feel free to have a go at that and if you share it here I'll take a
look.

**Pull request closed without merging**
