### PR TITLE
Make improvements to `FastHTML By Example`

### PR DESCRIPTION
**Pull request by hamelsmu**
Small PR as I'm working my way carefully through this document.  I suspect I will make multiple PRs onto this document. 

Changes made:

1. Use `serve()` instead of Uvicorn
2. Include links in places where there should be links
2. Make some of the language more succint (less is more)
3. Remove the bit about this doc serving as context because there is now `llm-ctx.txt` and friends
4. Update for new `@rt` decorator, and add a tabset panel so people can see the difference
5. Clarify some of the language assuming people are new to web development.
6. Move all `Asides` into Quarto callouts

Im only 25% of the way through just though I would open an early PR.  Don't want to make a big PR if these changes are not aligned with what you want to do!

>[!Important]
> I have generated [a preview link for the page I changed](https://66d0c49fad8823743fde7a8e--fasthtml-preview.netlify.app/tutorials/by_example) to make reviewing easier on Netlify

cc: @johnowhitaker @jph00

### CODE REVIEW

**Comment by jph00** [comment]
This is great! BTW the text "This is needed to tell FastHTML to turn the main body into a full HTML page that includes the headers (including the pico link and our custom css) which we passed in" is wrong. A single FT element is sufficient for this to work (cc @johnowhitaker since IIRC you wrote that bit)

**Comment by jph00** [comment]
@pydanny you might be interested in this PR to see some nice nbdev/quarto features icymi

**Comment by hamelsmu** [comment]
I'm a little confused by this

> "This is needed to tell FastHTML to turn the main body into a full HTML page that includes the headers (including the pico link and our custom css) which we passed in" is wrong. A single FT element is sufficient for this to work (cc @johnowhitaker since IIRC you wrote that bit)

I can't seem to figure out how to change the code exactly to do this without a tuple? 

```python
from fasthtml.common import *
css = Style(':root {--pico-font-size:90%,--pico-font-family: Pacifico, cursive;}') # <1>
app = FastHTML(hdrs=(picolink, css)) # <2>

@app.route("/")
def get():
    return (Title("Hello World"), 
               Main(H1('Hello, World'), cls="container"))
```

**Comment by jph00** [comment]
I've updated that sentence now to be more accurate.

**Pull request merged**
