### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jhi2**

### CODE REVIEW

**Comment by pydanny** [comment]
@jhi2 Thanks for adding a CoC, these things are really important!

Can you change it to the official [FastAI code of Conduct](https://github.com/fastai/fastcore/blob/master/CODE_OF_CONDUCT.md)?

**Comment by jhi2** [comment]
What is FastAI

**Comment by jph00** [comment]
Looks like you lost the formatting there. I'll copy it over myself.

**Comment by jhi2** [comment]
Sorry

**Comment by jph00** [comment]
No problem -- appreciate your contribution nonetheless!

**Pull request closed without merging**
