### PR TITLE
Fix html2ft edge cases, group custom attrs, add tests 

### PR DESCRIPTION
**Pull request by callmephilip**
---
name: Pull Request
about: Propose changes to the codebase
title: '[PR] '
labels: ''
assignees: ''

---

**Related Issue**

Current issues with html2f implementation

`<div x-transition:enter.scale.80 x-transition:leave.scale.90>hello</div>` incorrectly converts to `Div('hello', **{'x-transition:enter.scale.80':''}, **{'x-transition:leave.scale.90':''})`

`<div id="1">hello</div>` incorrectly converts to `Div('hello', id='1')` with `attrs1st=True`

(Not a bug but inconvenience): 

`Div('Hello 👋', x_show='open', **{'x-transition:enter':'transition duration-300'}, **{'x-transition:enter-start':'opacity-0 scale-90'})` <- custom attributes spread around multiple dictionaries as opposed to being grouped into 1 dictionary, e.g.

`Div('Hello 👋', x_show='open', **{'x-transition:enter':'transition duration-300', 'x-transition:enter-start':'opacity-0 scale-90'})`

**Proposed Changes**
This PR addresses the issues mentioned above ⬆️ and adds tests for htm2ft function

**Types of changes**
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @callmephilip ! Can you please run nbdev_export to fix CI?

**Comment by callmephilip** [comment]
> Thanks @callmephilip ! Can you please run nbdev_export to fix CI?

I tried the following multiple times:

```
nbdev_export && nbdev_clean && nbdev_trust
```

Still no luck. It seems like something has happened to [_modidx](https://github.com/AnswerDotAI/fasthtml/pull/581/files#diff-11e68a0207113f95e764d40371886549f1ad863bb7c8d92546a367e6dc0b4a7fR133-R664)

**Comment by jph00** [comment]
Try updating to the latest nbdev maybe?

**Comment by callmephilip** [comment]
nuked project directory and did a fresh checkout. looks good now

**Comment by jph00** [comment]
Many thanks :)

**Pull request merged**
