### PR TITLE
Add tailwind instructions to FAQ

### PR DESCRIPTION
**Pull request by rian-dolphin**
**Proposed Changes**
Add a section to the FAQ on how to setup tailwind following a request to do so from Jeremy in Discord.

### CODE REVIEW

**Comment by rian-dolphin** [comment]
See below for how it renders in the notebook.
Screenshot 2024-08-28 at 11 24 18
Screenshot 2024-08-28 at 11 24 30

**Review by pydanny — APPROVED** [review]
Hey @rian-dolphin this is awesome. However, I would argue this is a technical item, not a FAQ item. However, as Tailwind isn't an official part of FastHTML, it's more of a "tip" than a "explanation" or "reference".

@jph00, what do you think?

**Comment by rian-dolphin** [comment]
That makes sense. Do we want to have this type of additional information collated somewhere in the repo? If not I'll just make a blog post on Medium so others can still find it.

**Comment by phihung** [comment]
I found this medium [fasthtml-with-tailwind-css](https://medium.com/@pitvfx/fasthtml-with-tailwind-css-480b7590c79b ) that explains really well the configuration steps

**Comment by rian-dolphin** [comment]
Closing this since it doesn't quite fit an FAQ item as @pydanny pointed out.

**Pull request closed without merging**
